# Usa una imagen base de Python
FROM python:3.10

# Establece el directorio de trabajo
WORKDIR /app

# Instala dependencias del sistema
RUN apt-get update && apt-get install -y \
    python3-distutils \
    && rm -rf /var/lib/apt/lists/*
   
# Instala la librería de Kaggle
RUN pip install kaggle 
RUN pip install kaggle pandas

RUN mkdir -p /root/.kaggle


# Copia el script de descarga y procesamiento al contenedor
COPY ./pagina/kaggle/kagglescript.py /app/kagglescript.py

# Ejecuta el script para descargar y procesar los datos
CMD ["python3", "/app/kagglescript.py"]

