apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi  
  accessModes:
    - ReadWriteOnce  
  hostPath:
    path: ..\pagina\sql\data
  persistentVolumeReclaimPolicy: Retain  


