apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: ..\pagina\web
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual

