apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-rvolume
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: ..\pagina\web
